### ISSUE TITLE
meaning of 999999999999999999994 | random | to_uuid 

### ISSUE THREAD

**Issue by toralf** [ansible/ansible_collections_azure#1323] opened 2023-11-07 16:28 UTC
I do wonder about that code snippet e.g. in tests/integration/targets/azure_rm_adgroup/tasks/main.yml:
```
resource_prefix: "{{ 999999999999999999994 | random | to_uuid }}"
```
but did not found an explanation in the doc. _to_uuid_ is a 128 bit integer represented in hex notation. In that case IMO
```
{{ (2**128) | random | to_uuid }}
```
should be used to make use of the whole range.
If on the other hand a reproducible  PRNG sequence is wanted, then
```
... |random(seed=...) |  ...
```
should be preferred, no?

**Comment by Fred-sun** [comment] 2023-11-09 02:46
@toralf As '... |random(seed=...) |' , It will generate a fixed number, then it will correspond to the same UUIT, which is obviously not appropriate. The previous approach is to use a random number generated, and then generate the corresponding UUID, which is not wrong?

**Comment by Fred-sun** [comment] 2023-11-09 02:48
@toralf Using this expression "{{ (2**128) | random | to_uuid }}", it makes more sense.

**Comment by toralf** [comment] 2023-11-09 08:05
> @toralf As '... |random(seed=...) |' , It will generate a fixed number, then it will correspond to the same UUIT, which is obviously not appropriate. The previous approach is to use a random number generated, and then generate the corresponding UUID, which is not wrong?

the "test" path let ,me think that the test should be make using reliable output  my fault.

**Comment by Fred-sun** [comment] 2023-11-13 02:44
@toralf What do you mean by reliable? Increase the range of randomness?

**Comment by toralf** [comment] 2023-11-13 11:09
> @toralf What do you mean by reliable? Increase the range of randomness?

whilst my general motivation was this issue request is, that 
```
echo 2 ^ 128 | bc
340282366920938463463374607431768211456
```
is much bigger than the 999999999999999999994 (340282366920938463x to be precise) - I was in addition wondering, whether the 999999999999999999994 was used to have the same value in (unit test) in a reproducible way. But the later was just an assumption of mine.

**Comment by Fred-sun** [comment] 2023-11-13 12:41
@toralf I understand your idea, then I will expand this random number to 2**128. Thank you!

**Comment by Fred-sun** [comment] 2023-11-23 13:13
@toralf This just adds randomness, but is not a bug, and this use case will not be used directly in production (lack of permissions) as a demonstration, so close it for now. Thank you!

**Closed as completed** 2023-11-23 13:13 UTC
Labels: question, medium-priority, working
