### ISSUE TITLE
azure_rm_appgateway.py request_routing_rules rule_type choices wrong

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible_collections_azure#187] opened 2020-07-14 11:48 UTC
_From @frik4unix on Apr 07, 2020 10:48_

##### SUMMARY

The documentation for this module describes as choice for request_routing_rules.rule_type:

- basic
- path_based_routing

These choices are wrong - the correct ones are:

- Basic
- PathBasedRouting

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

lib/ansible/modules/cloud/azure/azure_rm_appgateway.py
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
```

##### CONFIGURATION

```paste below

    request_routing_rules:
      - rule_type: basic
        backend_address_pool: prod-app-gw-hosts
        backend_http_settings: http-8080
        http_listener: http-80
        name: http-to-https

```

##### ADDITIONAL INFORMATION

_Copied from original issue: ansible/ansible#68744_

**Comment by Akasurde** [comment] 2020-07-14 11:48
_From @Zype76 on Apr 11, 2020 04:12_

Hi there! 

I'm a newbie when it comes to contributing, so please forgive me if I mess up. 

It looks like the options in the documentation are in line with what's in the module's source. 

Additionally, I'm unsure if the case for basic would matter since Ansible's ConfigParser converts option names to lower case.

Does the module link below match what you're currently using for your replication? If not, it might help to reinstall it.

https://github.com/Azure/azure_preview_modules/blob/master/library/azure_rm_appgateway.py#L353

**Comment by Akasurde** [comment] 2020-07-14 11:48
_From @frik4unix on Apr 11, 2020 14:29_

Hi Zype,

yes, the documentation is in line with the module's source.
Of course the module's source is also wrong. I'm getting an error from 
Azure when using "basic".
If i use "Basic" it's working fine. So boht (module and configuration) 
are wrong.

Reinstall wouldn't help.

Am 11.04.20 um 06:12 schrieb Zype:

**Comment by Akasurde** [comment] 2020-07-14 11:48
_From @Zype76 on Apr 11, 2020 20:33_

Hi again! 

Hope you're having a good weekend. 

I took another peek, and I noticed that the rule_type options are being processed by the _snake_to_camel function in the link below. 

https://github.com/Azure/azure_preview_modules/blob/master/library/azure_rm_appgateway.py#L742

This should normally take the arguments "basic" or "path_based_routing" and filter them into the appropriate format for use by the sdk, however it looks like the if statement tied to the option is checking the parent dictionary.

This is preventing the check from running properly, and it's preventing the options from being converted into the desired format. Since I think the format in the documentation is desired, I've created the following pull request that should help address the issue. 

Someone from the Azure team will still need to review, approve and incorporate it, however I hope this helps! 

https://github.com/Azure/azure_preview_modules/pull/377

**Comment by Akasurde** [comment] 2020-07-14 11:48
_From @samccann on Apr 29, 2020 19:44_

Hi folks - is this something that needs to be fixed in both 2.9 and the collection that @Zype76 already has a PR for?

**Comment by Akasurde** [comment] 2020-07-14 11:48
_From @Fred-sun on May 12, 2020 08:36_

@frik4unix Thank you very much for your interest in Ansible. This repo is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure
Please re-submit this issue in the above repository and closed this. Thank you very much!

**Comment by Fred-sun** [comment] 2020-07-20 09:38
@Akasurde Thanks for your update! I'll look into it and if there's a real problem, I'll fix it. Thank you very much!

**Comment by Fred-sun** [comment] 2020-07-20 10:10
@Akasurde Can you update to the latest Ansible test again? Did I pass the test on 2.9.9. I tested PASS on 2.9.10. The return values are as follows:
```e.g.
            "request_routing_rules": [
                {
                    "backend_address_pool": {
                        "id": "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/applicationGateways/appgatewayfred002/backendAddressPools/test_backend_address_pool"
                    },
                    "backend_http_settings": {
                        "id": "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/applicationGateways/appgatewayfred002/backendHttpSettingsCollection/sample_appgateway_http_settings"
                    },
                    "http_listener": {
                        "id": "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/applicationGateways/appgatewayfred002/httpListeners/sample_http_listener"
                    },
                    "name": "rule1",
                    "rule_type": "basic"
                },
                {
                    "http_listener": {
                        "id": "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/applicationGateways/appgatewayfred002/httpListeners/http_listener"
                    },
                    "name": "http_redirect_rule",
                    "redirect_configuration": {
                        "id": "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/applicationGateways/appgatewayfred002/redirectConfigurations/redirect_site_to_https"
                    },
                    "rule_type": "basic"
                }
            ]

**Comment by Fred-sun** [comment] 2020-07-28 04:04
@Akasurde The definition in the document is only a description of the module parameters, the module will convert rule_type to the corresponding type through the "_snake_to_camel"  function . Transfermation as (‘basic'-->'Basic','path_based_routing' -->'PathBasedRouting'). So this is not a bug! Thank you very much!

**Comment by Fred-sun** [comment] 2020-08-05 06:51
If you have no other question. I will close this!

**Closed as completed by Fred-sun** 2020-08-05 06:51 UTC
