### ISSUE TITLE
No module named 'azure.storage.cloudstorageaccount'

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible_collections_azure#396] opened 2021-01-15 13:08 UTC
##### SUMMARY

Using collections with azure throws ModuleNotFoundError.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_publicipaddress_info

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /home/user/Ansible/ansible-dce/ansible.cfg
  configured module search path = ['/home/nbm/Ansible/repo/Modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### STEPS TO REPRODUCE

```
ansible-galaxy collection install azure.azcollection --force
```

```yaml
---

- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - azure.azcollection
  tasks:
  - name: get facts for public ip
    azure_rm_publicipaddress_info:
      tenant: '{{ tenant }}'
      client_id: '{{ client_id }}'
      secret: '{{ secret }}'
      subscription_id: '{{ subscription_id }}'
      resource_group: '{{ customer_prefix }}-sql'
    register: result

```

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ansible-test's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

```

**Comment by Fred-sun** [comment] 2021-01-26 03:25
@nicolaibaralmueller Thank you for submitting this problem. Judging from the log you submitted, it is caused by your environment. Can you reinstall the dependent package and retry? thank you
```e.g.
sudo pip3 install azure-cli

**Comment by nicolaibaralmueller** [comment] 2021-01-26 12:50
> @nicolaibaralmueller Thank you for submitting this problem. Judging from the log you submitted, it is caused by your environment. Can you reinstall the dependent package and retry? thank you
> 
> ```
> sudo pip3 install azure-cli 
> ```

Hi @Fred-sun. Result from installing azure-cli again:

```
sudo pip3 install azure-cli
Requirement already satisfied: azure-cli in /usr/local/lib/python3.8/dist-packages (2.12.1)
Requirement already satisfied: psutil~=5.7 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (5.7.2)
Requirement already satisfied: vsts-cd-manager>=1.0.2,~=1.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.0.2)
Requirement already satisfied: azure-appconfiguration~=1.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.1.1)
Requirement already satisfied: urllib3[secure]~=1.18 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.26.2)
Requirement already satisfied: azure-mgmt-redis~=7.0.0rc1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (7.0.0rc2)
Requirement already satisfied: azure-graphrbac~=0.60.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.60.0)
Requirement already satisfied: azure-batch~=9.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (9.0.0)
Requirement already satisfied: azure-mgmt-eventgrid==3.0.0rc7 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (3.0.0rc7)
Requirement already satisfied: azure-mgmt-containerservice~=9.4.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (9.4.0)
Requirement already satisfied: websocket-client~=0.56.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.56.0)
Requirement already satisfied: azure-mgmt-storage~=11.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (11.2.0)
Requirement already satisfied: azure-mgmt-devtestlabs~=4.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (4.0.0)
Requirement already satisfied: azure-mgmt-billing~=0.2 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-mgmt-dns~=2.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.1.0)
Requirement already satisfied: azure-mgmt-applicationinsights~=0.1.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.1)
Requirement already satisfied: azure-cosmos>=3.0.2,~=3.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (3.2.0)
Requirement already satisfied: azure-synapse-accesscontrol~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: antlr4-python3-runtime~=4.7.2 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (4.7.2)
Requirement already satisfied: azure-mgmt-batch~=9.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (9.0.0)
Requirement already satisfied: azure-multiapi-storage~=0.4.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.4.1)
Requirement already satisfied: azure-mgmt-security~=0.4.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.4.1)
Requirement already satisfied: azure-mgmt-containerregistry==3.0.0rc14 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (3.0.0rc14)
Requirement already satisfied: azure-loganalytics~=0.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.0)
Requirement already satisfied: azure-synapse-spark~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-mgmt-marketplaceordering~=0.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.1)
Requirement already satisfied: scp~=0.13.2 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.13.2)
Requirement already satisfied: azure-mgmt-appconfiguration~=0.6.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.6.0)
Requirement already satisfied: azure-mgmt-authorization~=0.61.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.61.0)
Requirement already satisfied: azure-mgmt-iotcentral~=3.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (3.0.0)
Requirement already satisfied: xmltodict~=0.12 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.12.0)
Requirement already satisfied: azure-mgmt-search~=2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.1.0)
Requirement already satisfied: azure-mgmt-recoveryservices~=0.4.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.4.0)
Requirement already satisfied: azure-mgmt-relay~=0.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.0)
Requirement already satisfied: azure-keyvault~=1.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.1.0)
Requirement already satisfied: azure-mgmt-keyvault==7.0.0b3 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (7.0.0b3)
Requirement already satisfied: azure-mgmt-synapse~=0.3.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.3.0)
Requirement already satisfied: azure-mgmt-containerinstance~=1.4 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.5.0)
Requirement already satisfied: azure-mgmt-sqlvirtualmachine~=0.5.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.5.0)
Requirement already satisfied: fabric~=2.4 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.5.0)
Requirement already satisfied: azure-functions-devops-build~=0.0.22 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.0.22)
Requirement already satisfied: azure-mgmt-loganalytics~=0.7.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.7.0)
Requirement already satisfied: azure-datalake-store~=0.0.49 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.0.50)
Requirement already satisfied: azure-mgmt-maps~=0.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.0)
Requirement already satisfied: azure-mgmt-policyinsights~=0.5.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.5.0)
Requirement already satisfied: azure-mgmt-media>=2.1.0,~=2.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.2.0)
Requirement already satisfied: azure-mgmt-trafficmanager~=0.51.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.51.0)
Requirement already satisfied: javaproperties==0.5.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.5.1)
Requirement already satisfied: azure-mgmt-imagebuilder~=0.4.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.4.0)
Requirement already satisfied: azure-mgmt-signalr~=0.4.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.4.0)
Requirement already satisfied: azure-storage-common~=1.4 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.4.2)
Requirement already satisfied: azure-mgmt-sql~=0.21.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.21.0)
Requirement already satisfied: azure-mgmt-kusto~=0.3.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.3.0)
Requirement already satisfied: sshtunnel~=0.1.4 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.5)
Requirement already satisfied: azure-mgmt-hdinsight~=1.7.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.7.0)
Requirement already satisfied: azure-mgmt-deploymentmanager~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-mgmt-datamigration~=0.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.0)
Requirement already satisfied: azure-mgmt-recoveryservicesbackup~=0.6.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.6.0)
Requirement already satisfied: azure-mgmt-iothub~=0.12.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.12.0)
Requirement already satisfied: azure-mgmt-datalake-analytics~=0.2.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.1)
Requirement already satisfied: azure-mgmt-datalake-store~=0.5.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.5.0)
Requirement already satisfied: azure-cli-core==2.12.1.* in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.12.1)
Requirement already satisfied: azure-mgmt-cognitiveservices~=6.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (6.2.0)
Requirement already satisfied: azure-mgmt-eventhub~=4.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (4.1.0)
Requirement already satisfied: azure-mgmt-consumption~=2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.0.0)
Requirement already satisfied: azure-mgmt-cosmosdb~=1.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.0.0)
Requirement already satisfied: azure-mgmt-msi~=0.2 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-mgmt-apimanagement~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-keyvault-administration~=4.0.0b1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (4.0.0b2)
Requirement already satisfied: azure-mgmt-reservations==0.6.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.6.0)
Requirement already satisfied: azure-mgmt-network~=12.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (12.0.0)
Requirement already satisfied: azure-mgmt-iothubprovisioningservices~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-mgmt-servicefabric~=0.5.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.5.0)
Requirement already satisfied: azure-mgmt-redhatopenshift==0.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.0)
Requirement already satisfied: azure-mgmt-web~=0.47.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.47.0)
Requirement already satisfied: azure-mgmt-advisor<3.0.0,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.0.1)
Requirement already satisfied: azure-mgmt-managedservices~=1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.0.0)
Requirement already satisfied: pytz==2019.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2019.1)
Requirement already satisfied: jsondiff==1.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (1.2.0)
Requirement already satisfied: azure-mgmt-rdbms~=3.0.0rc1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (3.0.0rc1)
Requirement already satisfied: azure-mgmt-cdn==5.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (5.0.0)
Requirement already satisfied: azure-mgmt-batchai~=2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.0.0)
Requirement already satisfied: cryptography<3.0.0,>=2.3.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.9.2)
Requirement already satisfied: jsmin~=2.2.2 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (2.2.2)
Requirement already satisfied: azure-mgmt-managementgroups~=0.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-mgmt-compute~=13.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (13.1.1)
Requirement already satisfied: azure-mgmt-monitor~=0.11.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.11.0)
Requirement already satisfied: azure-mgmt-netapp~=0.12.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.12.0)
Requirement already satisfied: azure-mgmt-privatedns~=0.1.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.1.0)
Requirement already satisfied: azure-mgmt-botservice~=0.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.2.0)
Requirement already satisfied: azure-mgmt-servicebus~=0.6.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli) (0.6.0)
Requirement already satisfied: mock in /usr/local/lib/python3.8/dist-packages (from vsts-cd-manager>=1.0.2,~=1.0.0->azure-cli) (4.0.2)
Requirement already satisfied: msrest>=0.2.0 in /usr/local/lib/python3.8/dist-packages (from vsts-cd-manager>=1.0.2,~=1.0.0->azure-cli) (0.6.19)
Requirement already satisfied: azure-core<2.0.0,>=1.2.2 in /usr/local/lib/python3.8/dist-packages (from azure-appconfiguration~=1.1.0->azure-cli) (1.10.0)
Requirement already satisfied: idna>=2.0.0; extra == "secure" in /usr/local/lib/python3.8/dist-packages (from urllib3[secure]~=1.18->azure-cli) (2.10)
Requirement already satisfied: pyOpenSSL>=0.14; extra == "secure" in /usr/local/lib/python3.8/dist-packages (from urllib3[secure]~=1.18->azure-cli) (19.1.0)
Requirement already satisfied: certifi; extra == "secure" in /usr/local/lib/python3.8/dist-packages (from urllib3[secure]~=1.18->azure-cli) (2020.12.5)
Requirement already satisfied: azure-common~=1.1 in /usr/local/lib/python3.8/dist-packages (from azure-mgmt-redis~=7.0.0rc1->azure-cli) (1.1.25)
Requirement already satisfied: msrestazure<2.0.0,>=0.4.32 in /usr/local/lib/python3.8/dist-packages (from azure-mgmt-redis~=7.0.0rc1->azure-cli) (0.6.4)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from websocket-client~=0.56.0->azure-cli) (1.15.0)
Requirement already satisfied: azure-mgmt-nspkg>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-mgmt-billing~=0.2->azure-cli) (3.0.2)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.8/dist-packages (from azure-cosmos>=3.0.2,~=3.0->azure-cli) (2.25.1)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from azure-multiapi-storage~=0.4.1->azure-cli) (2.7.3)
Requirement already satisfied: azure-nspkg>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-loganalytics~=0.1.0->azure-cli) (3.0.2)
Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (from scp~=0.13.2->azure-cli) (2.7.2)
Requirement already satisfied: azure-mgmt-core<2.0.0,>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-mgmt-keyvault==7.0.0b3->azure-cli) (1.2.0)
Requirement already satisfied: invoke<2.0,>=1.3 in /usr/local/lib/python3.8/dist-packages (from fabric~=2.4->azure-cli) (1.4.1)
Requirement already satisfied: vsts in /usr/local/lib/python3.8/dist-packages (from azure-functions-devops-build~=0.0.22->azure-cli) (0.1.25)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/dist-packages (from azure-functions-devops-build~=0.0.22->azure-cli) (2.11.2)
Requirement already satisfied: adal>=0.4.2 in /usr/local/lib/python3.8/dist-packages (from azure-datalake-store~=0.0.49->azure-cli) (1.2.4)
Requirement already satisfied: cffi in /usr/local/lib/python3.8/dist-packages (from azure-datalake-store~=0.0.49->azure-cli) (1.14.4)
Requirement already satisfied: azure-mgmt-datalake-nspkg>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-mgmt-datalake-analytics~=0.2.1->azure-cli) (3.0.1)
Requirement already satisfied: pkginfo>=1.5.0.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (1.5.0.1)
Requirement already satisfied: azure-cli-telemetry==1.0.6 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (1.0.6)
Requirement already satisfied: colorama~=0.4.1 in /usr/lib/python3/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (0.4.3)
Requirement already satisfied: msal-extensions~=0.1.3 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (0.1.3)
Requirement already satisfied: PyJWT in /usr/lib/python3/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (1.7.1)
Requirement already satisfied: jmespath in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (0.10.0)
Requirement already satisfied: msal~=1.0.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (1.0.0)
Requirement already satisfied: humanfriendly<9.0,>=4.7 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (8.2)
Requirement already satisfied: argcomplete~=1.8 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (1.12.1)
Requirement already satisfied: knack==0.7.2 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (0.7.2)
Requirement already satisfied: azure-mgmt-resource==10.2.0 in /usr/local/lib/python3.8/dist-packages (from azure-cli-core==2.12.1.*->azure-cli) (10.2.0)
Requirement already satisfied: requests-oauthlib>=0.5.0 in /usr/local/lib/python3.8/dist-packages (from msrest>=0.2.0->vsts-cd-manager>=1.0.2,~=1.0.0->azure-cli) (1.3.0)
Requirement already satisfied: isodate>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from msrest>=0.2.0->vsts-cd-manager>=1.0.2,~=1.0.0->azure-cli) (0.6.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.10.0->azure-cosmos>=3.0.2,~=3.0->azure-cli) (4.0.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3/dist-packages (from paramiko->scp~=0.13.2->azure-cli) (1.3.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko->scp~=0.13.2->azure-cli) (3.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/dist-packages (from jinja2->azure-functions-devops-build~=0.0.22->azure-cli) (1.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi->azure-datalake-store~=0.0.49->azure-cli) (2.20)
Requirement already satisfied: portalocker~=1.2 in /usr/local/lib/python3.8/dist-packages (from azure-cli-telemetry==1.0.6->azure-cli-core==2.12.1.*->azure-cli) (1.7.1)
Requirement already satisfied: applicationinsights<0.12,>=0.11.1 in /usr/local/lib/python3.8/dist-packages (from azure-cli-telemetry==1.0.6->azure-cli-core==2.12.1.*->azure-cli) (0.11.9)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.8/dist-packages (from knack==0.7.2->azure-cli-core==2.12.1.*->azure-cli) (5.3.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.8/dist-packages (from knack==0.7.2->azure-cli-core==2.12.1.*->azure-cli) (0.8.2)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (from knack==0.7.2->azure-cli-core==2.12.1.*->azure-cli) (2.7.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.5.0->msrest>=0.2.0->vsts-cd-manager>=1.0.2,~=1.0.0->azure-cli) (3.1.0)
```

And output is still the same:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ansible-test's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by sharik938** [comment] 2021-03-10 09:38
Same error as above
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on ansible-test's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

**Comment by l3ender** [comment] 2021-03-11 02:34
I'm not sure if it's related, but I've cloned this repo and have built/installed the latest of `dev` branch (and installed requirements in new virtual env). Once I run a playbook using any of the Azure collection modules, I get a similar error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.mgmt.recoveryservicesbackup'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on l3ender's Python /usr/local/opt/python@3.9/bin/python3.9. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by l3ender** [comment] 2021-03-13 04:29
For my issue, it was because I was using a virtual environment where the azure collection dependencies were installed, but I was using system-installed ansible. Installing ansible in my virtual environment solved the issue.

**Comment by nitinkansal1984** [comment] 2021-03-18 10:59
I am also facing the same issue
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on vm3's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

**Comment by nitinkansal1984** [comment] 2021-03-18 11:11
I was able to fix this by install all libraries https://github.com/ansible/ansible/blob/stable-2.8/packaging/requirements/requirements-azure.txt

**Comment by Fred-sun** [comment] 2021-05-28 05:32
@nitinkansal1984 If there are no other problems, I will close it. Thank you very much!

**Closed as completed** 2021-05-31 15:04 UTC
Labels: medium-priority, not-a-bug

**Comment by youssefbenfarhat** [comment] 2022-05-04 11:26
I still have the same error File "/tmp/ansible_azure_rm_virtualmachine_payload_64qpmb15/ansible_azure_rm_virtualmachine_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 249, in <module>
    from azure.storage.cloudstorageaccount import CloudStorageAccount
ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'

I'm using Miniconda Env with Python 3.9, I tried everything and still the same problem. I don't know whyy

**Comment by tonykay** [comment] 2022-05-20 19:29
I believe the primary issue is Microsoft has broken up `azure-storage` into smaller, more focussed libs. So you need to identify which storage libs you install. These are documented here: https://azure.github.io/azure-sdk/releases/latest/all/python.html

**Comment by maxnasonov** [comment] 2022-06-10 07:42
The module is called [azure.storage.common.cloudstorageaccount](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/cloudstorageaccount.py) now but `azure-storage==0.35.1` provides required module.

**Comment by dmaasland** [comment] 2022-07-21 10:23
Should anyone come across this in the future and not want to install an outdated library, it seems that **`azure.storage.cloudstorageaccount`** has moved to **`azure.storage.common.cloudstorageaccount`** and can be installed by running:

```bash
pip install azure-storage-common
```

**Comment by ahmedsza** [comment] 2022-09-26 11:14
I am hitting the same issue - and it occurs in the cloud shell. A basic sample like https://learn.microsoft.com/en-us/azure/developer/ansible/getting-started-cloud-shell?tabs=ansible is not working
if I run pip install azure-storage==0.35.1 it shows requirement is already satisfied

**Comment by madmalkav** [comment] 2022-10-11 08:42
> I am hitting the same issue - and it occurs in the cloud shell. A basic sample like https://learn.microsoft.com/en-us/azure/developer/ansible/getting-started-cloud-shell?tabs=ansible is not working if I run pip install azure-storage==0.35.1 it shows requirement is already satisfied

I'm in the same situation with Cloud Shell.

**Comment by Fred-sun** [comment] 2022-10-11 11:34
@nicolaibaralmueller  Could you help share the error log? Thank you very much!

**Comment by madmalkav** [comment] 2022-10-11 11:39
I think you perhaps wanted to mention me? in that case, my error is:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount' fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on cc-9beeda7-75c987bcd7-fznn5's Python /opt/ansible/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

**Comment by ahmedsza** [comment] 2022-10-11 11:52
@madmalkav  - I work at MS and raised this internally (on it not working on cloud shell). the team was able to repo the issue. The initial fix was part of a larger set of fixes that apparently had some issues - and it seems like a new deployment will happen later this month.. Note this is specific to cloud shell

**Comment by madmalkav** [comment] 2022-10-11 11:57
Thanks for keeping me updated. For information, I also raised this issue some days ago linked to the documentation explaining how to use Ansible on Cloud Shell: https://github.com/MicrosoftDocs/azure-dev-docs/issues/915

**Comment by jaybloodworth** [comment] 2022-10-17 18:49
I am having the same issue and not just with cloud shell; it is happening on a Debian 11 host as well. Is this just an issue with the current build? As noted above cloudstorageaccount is under azure.storage.common, not azure.storage.

**Comment by Fred-sun** [comment] 2022-10-18 00:10
@jaybloodworth Can you help provide your use cases and logs? This will help to have a solution to the current problem. Thank you very much!

**Comment by jaybloodworth** [comment] 2022-10-18 12:46
@Fred-sun Actually, I was able to get it working both under Debian and Cloud Shell by creating virtual environment, activating and installing ansible there, then doing `pip install -r lib/python3.9/site-packages/ansible_collections/azure/azcollection/requirements-azure.txt` from within the venv directory.

Furthermore, azcollection seems to be working with vanilla Cloud Shell as of today. I just tested it outside of the venv and with no .local directory and I was able to create a VM, Vnet, NIC, etc. as well as several resource groups.

**Comment by KrishnaG-MSFT** [comment] 2022-11-09 14:35
Hello @Fred-sun, Did the new deployment happen as mentioned by @ahmedsza in an earlier comment ? Please share an update. Thank you.

**Comment by ahmedsza** [comment] 2022-11-09 14:41
@KrishnaG-MSFT  - according to an internal note I got, the deployment did happen - and the issue was fixed. I was on leave at that time so did not have a chance to test

**Comment by rahulsoni43** [comment] 2022-11-10 14:14
Guys, what is the fix for this issue.. i tried as mentioned by @jaybloodworth but looks like still the smae issue..

``` 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on c27e707550f8's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by ghost** [comment] 2022-11-18 16:17
I pinned my version of `azure.azcollections` to `1.13.0` and our stuff started working again. WIth the latest version `1.14.0`, I was seeing the same errors you all reported above. 

```
# Install Ansible Azure collection dependencies
RUN ansible-galaxy collection install azure.azcollection:==1.13.0 \
    && pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
```

**Comment by rahul-chr** [comment] 2022-11-20 05:38
@pfinnerty thanks Man... you saved lot of time.. it worked like charm.

**Comment by manumittal89** [comment] 2022-11-27 17:20
Hello ,
I am also facing the same issue but unable to fine the solution .Can you please advise me on the same ...

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on a8ee211c8a25's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

**Comment by ppodgorsek** [comment] 2023-09-18 15:38
Having a similar error when running jobs via Ansible AWX/Tower, I eventually realised there was a discrepancy between the versions of the Azure Collection we were using:
* version 1.17.0 was installed in the AWX execution environment,
* version 1.13.0 was declared in the infrastructure-as-code repository.

Ensuring both were using version 1.17.0 made this storage error disappear.

Hopefully this might help others who have a similar problem.

**Comment by pbrisson73** [comment] 2023-09-19 21:06
> Having a similar error when running jobs via Ansible AWX/Tower, I eventually realised there was a discrepancy between the versions of the Azure Collection we were using:
> 
> * version 1.17.0 was installed in the AWX execution environment,
> * version 1.13.0 was declared in the infrastructure-as-code repository.
> 
> Ensuring both were using version 1.17.0 made this storage error disappear.
> 
> Hopefully this might help others who have a similar problem.

Thank you @ppodgorsek , that fixed my issue with AWX.
