### ISSUE TITLE
Missing features in network client

### ISSUE THREAD

**Issue by Conor0Callaghan** [ansible/ansible_collections_azure#1119] opened 2023-03-22 14:13 UTC
##### SUMMARY

Issues with unsupported options when running examples in Ansible documentation https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_securitygroup_module.html  . Submitting patch to upgrade version of API and fix issue. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Network client in module common

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.8]
  config file = None
  configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/testuser/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/testuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/testuser/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
community.general 5.8.3
```

##### OS / ENVIRONMENT

Ubuntu 20.04.1 LTS

##### STEPS TO REPRODUCE

```yaml

- name: Get current public IP address
  ansible.builtin.command: 'curl icanhazip.com'
  register: public_ip

- azure_rm_securitygroup:
    resource_group: MYRG
    name: remoterg
    rules:
        - name: SSH_ACCESS
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
          source_address_prefix: "{{ public_ip.stdout }}/32"

```

##### EXPECTED RESULTS

Changed IP in the resource group.

##### ACTUAL RESULTS

```paste below
    redirecting (type: modules) ansible.builtin.azure_rm_securitygroup to azure.azcollection.azure_rm_securitygroup
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: testuser
<127.0.0.1> EXEC /bin/sh -c 'echo ~testuser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/testuser/.ansible/tmp `"&& mkdir "` echo /home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819 `" && echo ansible-tmp-1679494254.7852762-7977-168992109254819="` echo /home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.azure_rm_securitygroup to azure.azcollection.azure_rm_securitygroup
Using module file /home/testuser/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py
<127.0.0.1> PUT /home/testuser/.ansible/tmp/ansible-local-7941k6j4f488/tmprzzjj2xc TO /home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/ /home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py", line 107, in <module>
    _ansiballz_main()
  File "/home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_securitygroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_securitygroup', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py", line 834, in <module>
  File "/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py", line 830, in main
  File "/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py", line 667, in __init__
  File "/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py", line 675, in exec_module
  File "/home/testuser/.local/lib/python3.8/site-packages/azure/mgmt/network/_network_management_client.py", line 4774, in network_security_groups
    raise ValueError("API version {} does not have operation group 'network_security_groups'".format(api_version))
ValueError: API version 2021-03-01 does not have operation group 'network_security_groups'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/testuser/.ansible/tmp/ansible-tmp-1679494254.7852762-7977-168992109254819/AnsiballZ_azure_rm_securitygroup.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_securitygroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_securitygroup', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py\", line 834, in <module>\n  File \"/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py\", line 830, in main\n  File \"/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py\", line 667, in __init__\n  File \"/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure_rm_securitygroup_payload_nv_ciofc/ansible_azure_rm_securitygroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup.py\", line 675, in exec_module\n  File \"/home/testuser/.local/lib/python3.8/site-packages/azure/mgmt/network/_network_management_client.py\", line 4774, in network_security_groups\n    raise ValueError(\"API version {} does not have operation group 'network_security_groups'\".format(api_version))\nValueError: API version 2021-03-01 does not have operation group 'network_security_groups'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by Fred-sun** [comment] 2023-03-24 09:01
@Conor0Callaghan  I did not encounter your problem in the local test. Could you please check the versions of ansible-collection and azure-mgmt-network that you use? Thank you very much!

**Comment by Conor0Callaghan** [comment] 2023-03-24 09:31
> @Conor0Callaghan I did not encounter your problem in the local test. Could you please check the versions of ansible-collection and azure-mgmt-network that you use? Thank you very much!

Sure no problem, here are the details

```
Collection        Version
----------------- -------
community.general 5.8.3

Name: azure-mgmt-network
Version: 21.0.1
```

If it helps this is the file I modified to get my ansible code to work:

``~/.ansible/collections/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py``

**Comment by Fred-sun** [comment] 2023-03-24 09:58
@Conor0Callaghan Now we specify the following version, I suggest you install and try again, thank you!
```e.g.
sudo pip3 install azure-mgmt-network==19.1.0 -I
ansible-galaxy collection install azure.azcollection --force

**Comment by Conor0Callaghan** [comment] 2023-03-24 10:43
> @Conor0Callaghan Now we specify the following version, I suggest you install and try again, thank you!
> 
> ```
> sudo pip3 install azure-mgmt-network==19.1.0 -I
> ansible-galaxy collection install azure.azcollection --force
> ```

That was it! It works after applying the fix again from  https://github.com/Azure/azure-sdk-for-python/issues/28757#issuecomment-1448729884 everything works as expected! I'll close the PR and the ticket. Apologies you had to test it out!

Perhaps we can add it to the ansible documentation as it's a bit unclear to a new user why this wouldn't work?

**Comment by Fred-sun** [comment] 2023-03-27 13:57
@Conor0Callaghan Thanks for your trying! I will closed it!

**Closed as completed by Fred-sun** 2023-03-27 13:57 UTC
Labels: bug, has-pr, medium-priority, hold

**Comment by fkupchik** [comment] 2023-04-17 10:17
The above solution didn't fully work for me. The original error is gone but now I'm getting the following error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'RecoveryServicesBackupClient' from 'azure.mgmt.recoveryservicesbackup' (/usr/local/lib/python3.11/site-packages/azure/mgmt/recoveryservicesbackup/__init__.py)
```
Should I also downgrade `azure.mgmt.recoveryservicesbackup`? If yes, why and what version should be used?

Also, what's the reason to downgrade azure-mgmt-network to `19.1.0` from newer version?
```
Installing collected packages: azure-mgmt-network
  Attempting uninstall: azure-mgmt-network
    Found existing installation: azure-mgmt-network 23.0.0
    Uninstalling azure-mgmt-network-23.0.0:
      Successfully uninstalled azure-mgmt-network-23.0.0
Successfully installed azure-mgmt-network-19.1.0
```

Don't we loose the functionality implemented in new version of the package? This sounds like a regression.

**Comment by Fred-sun** [comment] 2023-04-17 12:38
@fkupchik Follow the latest ansible-collection version and its dependent library files. Thanks!
```e..g.
ansible-galaxy collection install azure.azcollection --force
pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
