### ISSUE TITLE
azure_rm_storageaccount module not passing https_only true - only passes false to Azure

### ISSUE THREAD

**Issue by aut0m4te** [ansible/ansible_collections_azure#184] opened 2020-07-08 20:29 UTC
##### SUMMARY

In the azure_rm_storageaccount module, the 'https_only' flag value always seems to pass 'false' to Azure when run, even when set to true or yes.

This could also have some relation to this bug formerly reported:  https://github.com/ansible/ansible/issues/60528
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

  azure_rm_storageaccount

##### ANSIBLE VERSION

```paste below
[root@crpitsawx98 ~]# ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/apps/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:6379:0
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/apps/ansible/inventories/dev/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /apps/ansible/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/apps/ansible/library']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = [u'/apps/ansible/module_utils']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/apps/ansible/roles']
```

##### OS / ENVIRONMENT

Target is just the Azure cloud - storage accounts in Azure.

##### STEPS TO REPRODUCE

Code sample to reproduce:

- name: Create storage account
  azure_rm_storageaccount:
    resource_group: "{{ valid_azure_resourcegroup.state.name }}"
    name: "unique_storageacctname_12345"
    location: centralus
    access_tier: Hot
    account_type: Standard_LRS
    kind: StorageV2
    https_only: true
  register: storageaccount_status

# ## output for storage account ##
- name: output storageaccount info
  debug:
    var: storageaccount_status

Debug output will show that https_only value is always passed as  false
You can try any of these in https_only:
  true
  yes
  'true'
with the same results

```yaml
- hosts: localhost
  connection: local
  roles:
    - { role: azure.azure_modules }
  
  tasks:
    - name: Create storage account
       azure_rm_storageaccount:
         resource_group: "{{ valid_azure_resourcegroup.state.name }}"
         name: "unique_storageacctname_12345"
         location: centralus
         access_tier: Hot
         account_type: Standard_LRS
         kind: StorageV2
         https_only: true
       register: storageaccount_status

    - name: output storageaccount
      debug:
        var: storageaccount_status
```

##### EXPECTED RESULTS

Expected to have the param for https_only match the correct value being passed to Azure and to be able to create storage accounts with the https_only flag set to true since that feature is available in Azure and the Ansible module documents that it should be working.

##### ACTUAL RESULTS

https_only passes false, even when 'true' is provided as the value in the key-value pair.

```paste below
Do not currently have a screen shot of the output... if this is critical, please let me know, but it's just the JSON output showing this:

"https_only:"  "false"

in the debug output.
```

**Comment by Fred-sun** [comment] 2020-07-14 02:44
@djstratman Thank you for reporting this problem. I tested it locally and did not encounter the problem you mentioned? You did not use ansible_collection to create, because there is no namespace specified. You need to change as follows. Thank you!
```e.g.

1. set namespace --refrence link:  https://github.com/ansible-collections/azure
  collections:
    - azure.azcollection

2.   Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.

**Comment by Fred-sun** [comment] 2020-07-20 10:20
@djstratman Any update for this! If you have no other comments, I will close it. If there are any new questions, please feel free to resubmit them! Thank you very much!

**Closed as completed by Fred-sun** 2020-07-20 10:20 UTC

**Comment by aut0m4te** [comment] 2020-07-21 01:03
@Fred-sun I am not able to replicate getting this working.  Can you show me that the https_only flag works?  I would like some working code that shows the code works so that I am able to replicate the correct behavior.  Would you mind providing a code block of the module that you were able to create a storage account with in Azure with the 'https_only' set to true?

**Comment by Fred-sun** [comment] 2020-07-21 01:29
@djstratman Playbook and result as follow:
```e.g.
- hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Create storage account
      azure_rm_storageaccount:
        resource_group: v-xisuRG
        name: "uniquestorageacctname12"
        location: centralus
        access_tier: Hot
        account_type: Standard_LRS
        kind: StorageV2
        https_only: true

    - name: Get storage account
      azure_rm_storageaccount_info:
        resource_group: v-xisuRG
        name: "uniquestorageacctname12"
      register: output
    - name:
      debug:
        var: output.storageaccounts[0].https_only
```
result:
```e.g
PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Create storage account] ******************************************************************************************
ok: [localhost]

TASK [Get storage account] *********************************************************************************************
ok: [localhost]

TASK [debug] ***********************************************************************************************************
ok: [localhost] => {
    "output.storageaccounts[0].https_only": true

**Comment by aut0m4te** [comment] 2020-07-21 05:20
@Fred-sun  - thank you.  I will try this out tomorrow and get back.

**Comment by aut0m4te** [comment] 2020-07-22 17:32
@Fred-sun - tested today.  I confirmed that the azure collections worked perfectly on the https_only flag.  I also confirmed that on Ansible core (at the latest), it still keeps the value "false" when you provide the 'true' param.

Do you think this is worth reporting?  I ended up submitting this bug in ansible-collections/azure because the last bug I saw submitted for the Azure modules in ansible core was pushed over here.

I guess the question is --
1) How do we ensure ansible-core knows this bug exists on their latest and
2) that eventually this fixed code in the ansible azure collections updates ansible core?

Thank you, again, for all of your help, sir!

**Comment by arsenicks** [comment] 2021-03-11 06:00
@Fred-sun I'm having this exact same issue and I confirm I am using the ansible collection. Could you reopen this issue so we won't loose discussion history please ? If you can reopen it I'll add all my details, logs and finding here.

Thanks

**Comment by arsenicks** [comment] 2021-03-11 06:33
Well I have the logs here so I'll post it now and I'll just copy it into a new issue if needed.

First, it's interesting to note that if I execute my playbook and no storage account exist the creation complete successfully but the https_only option is not set as it was set in the playbook. But if I run my playbook again the https_only option will be used and the existing storage account will be updated..

Collection version:
```
$ ansible-galaxy collection list

# /home/XXXX/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.4.0  
```

Playbook:
```
---
- name: Create RG and secure storage account
  hosts: localhost
  gather_facts: false
  collections:
    - azure.azcollection

  tasks:

  - name: Create RG
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ item }}"
      location: canadacentral
    loop:
      - rg01

  - name: Create storage account true
    azure.azcollection.azure_rm_storageaccount:
      resource_group: rg01
      https_only: true
      name: "{{ item }}"
      kind: StorageV2
      type: Standard_LRS
      allow_blob_public_access: no
    loop:
      - pp9901
      - pp9902
```


Ansible-playbook output using -vvv
```
[...]
using module file /home/XXXX/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageaccount.py
[...]
changed: [localhost] => (item=pp9901) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "access_tier": null,
            "account_type": "Standard_LRS",
            "ad_user": null,
            "adfs_authority_url": null,
            "allow_blob_public_access": false,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "blob_cors": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "custom_domain": null,
            "force_delete_nonempty": false,
            "https_only": true,
            "kind": "StorageV2",
            "location": null,
            "minimum_tls_version": null,
            "name": "pp9901",
            "network_acls": null,
            "password": null,
            "profile": null,
            "resource_group": "rg01",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "type": "Standard_LRS"
        }
    },
    "item": "pp9901",
    "state": {
        "access_tier": "Hot",
        "allow_blob_public_access": false,
        "custom_domain": null,
        "https_only": false,
        "id": "/subscriptions/XXXXXXXXXXXXX/resourceGroups/rg01/providers/Microsoft.Storage/storageAccounts/pp9901",
        "location": "canadacentral",
        "minimum_tls_version": null,
        "name": "pp9901",
        "network_acls": {
            "bypass": "AzureServices",
            "default_action": "Allow",
            "ip_rules": [],
            "virtual_network_rules": []
        },
        "primary_endpoints": {
            "blob": "https://pp9901.blob.core.windows.net/",
            "queue": "https://pp9901.queue.core.windows.net/",
            "table": "https://pp9901.table.core.windows.net/"
        },
        "primary_location": "canadacentral",
        "provisioning_state": "Succeeded",
        "resource_group": "rg01",
        "secondary_endpoints": null,
        "secondary_location": null,
        "sku_name": "Standard_LRS",
        "sku_tier": "Standard",
        "status_of_primary": "available",
        "status_of_secondary": null,
        "tags": null,
        "type": "Microsoft.Storage/storageAccounts"
    }
}
```
As you can see the module_args show clearly that ""https_only": true" is set and we can see in the state that it's not set ""https_only": false"

Azure activity log output confirm the problem is not on azure side, azure receive supportsHttpsTrafficOnly to false:
```
    "properties": {
        "requestbody": "{\"sku\":{\"name\":\"Standard_LRS\",\"tier\":\"Standard\"},\"kind\":\"StorageV2\",\"location\":\"canadacentral\",\"properties\":{\"supportsHttpsTrafficOnly\":false,\"allowBlobPublicAccess\":false}}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/XXXXXXXXXXXXXXXXX/resourceGroups/rg01/providers/Microsoft.Storage/storageAccounts/pp9901",
        "message": "Microsoft.Storage/storageAccounts/write",
    },
```
