### ISSUE TITLE
Cannot create private endpoint - API version problem

### ISSUE THREAD

**Issue by bilpyt** [ansible/ansible_collections_azure#1727] opened 2024-09-25 08:25 UTC
##### SUMMARY
When I want create new private enpoint for redis it fails with error:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: 'private_endpoints' is not available in API version 2021-03-01. All valid API version are 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-02-01, 2023-02-01, 2023-04-01, 2023-05-01, 2023-06-01, 2023-09-01, 2023-11-01, 2024-01-01.`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_privateendpoint

##### ANSIBLE VERSION

```
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/ansible/azure-env/lib/python3.12/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/azure-env/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/home/xxx/azure-env/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/xxx/azure-env/lib/python3.12/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 9.4.0  

# /home/xxx/azure-env/lib/python3.12/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.7.0 
```

##### CONFIGURATION

```
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

Ubuntu 24.04.1 LTS - 64bit, GNOME 46, X11, Linux 6.8.0-45-generic

##### STEPS TO REPRODUCE

Just play playbook with deploy of redis and privateendpoint. Redis deploys OK.

`./azure-env/bin/ansible-playbook -i hosts.yaml playbook-deploy-redis.yaml`

Role azure_redis
```
---
- name: Create Azure Cache for Redis instance
  azure.azcollection.azure_rm_rediscache:
    resource_group: "{{ resource_group }}"
    name: "{{ redis_name }}"
    location: "{{ location }}"
    sku:
      name: "{{ sku }}"
      size: "{{ size }}"
    tags:
      environment: dev

- name: Create Private Endpoint for Redis
  azure.azcollection.azure_rm_privateendpoint:
    resource_group: "{{ resource_group }}"
    name: "{{ private_endpoint_name }}"
    #location: "{{ location }}"
    subnet:
      id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ vnet_name }}/subnets/{{ subnet_name }}"
    private_link_service_connections:
      - name: redisConnection
        private_link_service_id: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Cache/redis/{{ redis_name }}"
        group_ids:
          - redisCache
    tags:
      environment: dev

```

Hosts.yaml
```
all:
  hosts:
    localhost:
      ansible_connection: local
```

playbook-deploy.redis.yaml
```
---
- name: Deploy Azure Cache for Redis and Private Endpoint
  hosts: localhost
  vars_files:
    - group_vars/vars_dev.yaml 
  connection: local
  gather_facts: no

  roles:
    - role: azure_redis
```

vars_dev.yaml - XYZ values are for anonymization...
```
azure_subscription_id: "XYZ"
#Toto se využije jen se Service Principals
resource_group: "XYZ"
redis_name: "redis-XYZ-dev"
vnet_name: "vnet-XYZ-dev"
subnet_name: "xyzSubnet"
private_endpoint_name: "pep-redis-XYZ-dev"
location: "XYZ"
dns_zone: "redis-XYZ-dev.redis.cache.windows.net"
sku: "standard"
size: "C0"

```

##### EXPECTED RESULTS

Successful deploy of Private endpoint for redis

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/home/XXX/.ansible/tmp/ansible-tmp-1727252488.8371315-99282-54749617202394/AnsiballZ_azure_rm_privateendpoint.py", line 107, in <module>
    _ansiballz_main()
  File "/home/XXX/.ansible/tmp/ansible-tmp-1727252488.8371315-99282-54749617202394/AnsiballZ_azure_rm_privateendpoint.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/XXX/.ansible/tmp/ansible-tmp-1727252488.8371315-99282-54749617202394/AnsiballZ_azure_rm_privateendpoint.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_privateendpoint', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_privateendpoint', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py", line 341, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py", line 337, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py", line 228, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 474, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py", line 250, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py", line 302, in get_resource
  File "/home/XXX/azure-env/lib/python3.12/site-packages/azure/mgmt/network/_validation.py", line 25, in wrapper
    raise ValueError(
ValueError: 'private_endpoints' is not available in API version 2021-03-01. All valid API version are 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-02-01, 2023-02-01, 2023-04-01, 2023-05-01, 2023-06-01, 2023-09-01, 2023-11-01, 2024-01-01.
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1727252488.8371315-99282-54749617202394/AnsiballZ_azure_rm_privateendpoint.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1727252488.8371315-99282-54749617202394/AnsiballZ_azure_rm_privateendpoint.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/XXX/.ansible/tmp/ansible-tmp-1727252488.8371315-99282-54749617202394/AnsiballZ_azure_rm_privateendpoint.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_privateendpoint', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_privateendpoint', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py\", line 341, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py\", line 337, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py\", line 228, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 474, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py\", line 250, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_privateendpoint_payload_ks2qkr16/ansible_azure.azcollection.azure_rm_privateendpoint_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_privateendpoint.py\", line 302, in get_resource\n  File \"/home/XXX/azure-env/lib/python3.12/site-packages/azure/mgmt/network/_validation.py\", line 25, in wrapper\n    raise ValueError(\nValueError: 'private_endpoints' is not available in API version 2021-03-01. All valid API version are 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-02-01, 2023-02-01, 2023-04-01, 2023-05-01, 2023-06-01, 2023-09-01, 2023-11-01, 2024-01-01.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}


```

**Comment by Fred-sun** [comment] 2024-09-26 03:02
@bilpyt This error is caused by your environment installation of azure-mgmt-network version higher than v19.1.0.  Please specify azure-Mgmt-network ==19.1.0. Thank you!

In addition, we have upgraded azure-mgmt-network==26.0.0, related PR  #1697. It will be released in the next release, expected in mid-October. Thank you!

**Comment by bilpyt** [comment] 2024-09-26 11:32
Thank you - after `pip azure-mgmt-network==19.1.0` it works...
And I have question - how can I solve this in future alone? Did I missed somethink?
I install dependencies from `https://raw.githubusercontent.com/ansible-collections/azure/refs/heads/dev/requirements.txt` and there is version 26.0.0...

**Comment by Fred-sun** [comment] 2024-09-26 12:13
@bilpyt I'm very sorry for the trouble. The next release will include these. Thank you!

**Closed as completed by Fred-sun** 2024-09-26 12:13 UTC
Labels: medium-priority, not-a-bug, working
