### ISSUE TITLE
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to determine PowerState of virtual machine rhel93-boys-01"}

### ISSUE THREAD

**Issue by tux1980** [ansible/ansible_collections_azure#1371] opened 2023-12-12 07:29 UTC
I cannot start install any Red HAt Linux System (Marketplace Instance) since I always get the messsage: Failed to determine PowerState of virtual machine rhel93-01"}.

Even the setting is apprantly okay with "started: "true" - that is the only Power Setting I know.
 image:
          started: "{{ started_the_vm }}"
          offer: "{{ offer_rhel }}"
          publisher: "{{ publisher_redhat }}"
          sku: "{{ linux_vm_sku }}"
          version: "{{ version_rhel }}" 

##### SUMMARY
I'm using the newest Ansible collections and executing the playbook via a RED Hat ansible Controller (Version 4.4.8).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to determine PowerState of virtual machine rhel93-boys-01"})-->

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION
azure.azcollection 2.0.0 

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Fred-sun** [comment] 2023-12-13 05:41
@tux1980 Thanks for reporting the problem, could you share your test case? This is a better way to solve your problems, thank you!

**Comment by Fred-sun** [comment] 2024-01-05 08:18
@tux1980 I am very sorry for replying to your question so late. I did not encounter the problem you submitted after repeated local tests, and this error is caused by VM status. Previously, there was a PR #1354 dedicated to detecting VM status after VM creation, can you update to the latest branch to check if your problem still exists? Thank you!

**Comment by Fred-sun** [comment] 2024-01-09 02:58
Any feedback?

**Comment by Fred-sun** [comment] 2024-01-16 12:57
Duplicate of #1365

**Comment by Fred-sun** [comment] 2024-01-18 09:51
@tux1980 This problem is very beggar, and I cannot copy it for the time being, so I have tested 'powerstate' in PR#1412. You can update to the branch of 1412, will you still encounter this problem? Thank you!

**Comment by Fred-sun** [comment] 2024-01-19 01:31
kindly ping!

**Closed as completed** 2024-01-22 06:02 UTC
Labels: duplicate, question, has-pr, medium-priority
