### ISSUE TITLE
Error retrieving available machine sizes - APIVersion 2019-07-01 is not available

### ISSUE THREAD

**Issue by henti** [ansible/ansible_collections_azure#339] opened 2020-11-26 16:56 UTC
##### SUMMARY
Trying to deploy VM in Azure, fails with erro. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION
```paste below
ansible 2.10.3
  config file = /home/henti/src/ansible/ansible.cfg
  configured module search path = ['/home/henti/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/henti/.local/lib/python3.6/site-packages/ansible
  executable location = /home/henti/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_FORKS(/home/henti/src/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/henti/src/ansible/ansible.cfg) = ['/home/henti/src/ansible/inventory.d']
DEFAULT_JINJA2_EXTENSIONS(/home/henti/src/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_LOG_PATH(/home/henti/src/ansible/ansible.cfg) = /home/henti/logs/ansible.log
DEFAULT_MANAGED_STR(/home/henti/src/ansible/ansible.cfg) = Ansible managed
DEFAULT_ROLES_PATH(/home/henti/src/ansible/ansible.cfg) = ['/home/henti/src/ansible/roles', '/home/henti/src/ansible']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
DEFAULT_VAULT_PASSWORD_FILE(/home/henti/src/ansible/ansible.cfg) = /home/henti/src/ansible/scripts/get_vault_password.sh
INTERPRETER_PYTHON(/home/henti/src/ansible/ansible.cfg) = python2
INVENTORY_IGNORE_EXTS(/home/henti/src/ansible/ansible.cfg) = ['.ini']
```

##### OS / ENVIRONMENT
Linux Mint 19.3 Tricia

##### STEPS TO REPRODUCE

```yaml
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{resourcegroups.name}}"
      subscription_id: "{{resourcegroups.subscription_id}}"
      auth_source: cli
      os_disk_size_gb: 128
      managed_disk_type: Premium_LRS
      name: "{{vm_name}}-{{ ansible_date_time.date }}"
      vm_size: Standard_F8s_v2
      admin_username: admin
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/admin/.ssh/authorized_keys
          key_data: "{{ lookup('file', 'ssh_keys/henti-henti-rsa') }}"
      network_interfaces: "{{vm_name}}-nic-{{ ansible_date_time.date }}"
      image:
        offer: debian-10
        publisher: Debian
        sku: '10'
        version: latest
```

##### EXPECTED RESULTS
VM Created

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_azure_rm_virtualmachine_payload_tw6rl90i/ansible_azure_rm_virtualmachine_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine.py", line 1989, in vm_size_is_valid
  File "/home/henti/.local/lib/python3.6/site-packages/azure/mgmt/compute/compute_management_client.py", line 668, in virtual_machine_sizes
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
```

**Comment by wadhwasam** [comment] 2020-12-10 16:24
Hi Henti, Did you find any luck, I am facing the same issue and looking for solution.

Thanks,
Sam

**Comment by henti** [comment] 2020-12-11 11:22
Hi @wadhwasam 

I've not made any further progress, This is a blocker on one of my projects currently.

**Comment by mytuanZ** [comment] 2020-12-13 11:08
Hello,
I got the same issue when I tried with this playbook:

- name: provision new Azure virtual host
    azure_rm_virtualmachine:
      admin_username: admintest
      admin_password: "{{ vm_password }}"
      os_type: Windows
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
      name: "{{ vm_name }}"
      resource_group: "{{ resource_group }}"
      state: present
      vm_size: Standard_B2s
      virtual_network_name: vnet-11
      subnet_name: snet1

Follow this page: https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-07-01/virtualmachines , Standard_B2s is in the list.
`The full traceback is:
  File "/tmp/ansible_azure_rm_virtualmachine_payload_tw8hpvxm/ansible_azure_rm_virtualmachine_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualmachine.py", line 1989, in vm_size_is_valid
  File "/home/anzureuser/.local/lib/python3.6/site-packages/azure/mgmt/compute/compute_management_client.py", line 668, in virtual_machine_sizes
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
...
"msg": "Error retrieving available machine sizes - APIVersion 2019-07-01 is not available"
}
`

**Comment by Fred-sun** [comment] 2020-12-16 08:23
@henti Thank you very much for reporting this issue, we are investigating and will reply as soon as possible! Thank you!

**Comment by Fred-sun** [comment] 2020-12-16 09:17
@henti  @mytuanZ My test has no problem, can you re-test according to the dependency package? thank you very much!
```e.g.
sudo pip3 install -r requirements-azure.txt -I

[requirements-azure.txt](https://github.com/ansible-collections/azure/files/5701556/requirements-azure.txt)

**Comment by henti** [comment] 2020-12-16 09:51
I've installed the dependencies and tried again. Same issue: 

[azure.log](https://github.com/ansible-collections/azure/files/5701748/azure.log)

**Comment by henti** [comment] 2020-12-16 09:55
It seems I needed to not do it with `sudo` which now seems to work.

**Comment by Fred-sun** [comment] 2020-12-17 07:19
> It seems I needed to not do it with `sudo` which now seems to work.

@henti  Thank you for your reply. Now that has to work, it should be caused by the environment. Can we close this issue temporarily? Thank you very much!

**Closed as completed** 2020-12-17 08:08 UTC
Labels: medium-priority, working
