### ISSUE TITLE
Unable to login to azure portal with the exported variable or credential file entries

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible_collections_azure#548] opened 2021-05-27 04:35 UTC
_From @rajaniesh on May 27, 2021 00:25_

### Summary

Hi,

I have followed this article  https://docs.ansible.com/ansible/2.3/guide_azure.html. IN this when I used service principal it works fine but when I tried using 

[default]
ad_user=XXXXX
password=YYYYY
subscription_id=zzzzzzz

it does not work I tried using the environment variable and tried passing the parameters like this 
 ansible-playbook CreateAzureVM.yml --extra-vars "ad_user=xxxx password=yyyy subscription_id=zzzz" -vvv

but it does not work and throws this error. In fact I tried using az login but the same issue

Regards
Rajaniesh

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/azureuser/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/azureuser/.local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

CentOS 8

### Steps to Reproduce

```yaml (paste below)
 ansible-playbook CreateAzureVM.yml --extra-vars "ad_user=xxxx password=yyyy subscription_id=zzzz" -vvv

```

### Expected Results

It is expected to create a VM but it is struck up in the authentication itslef

### Actual Results

```console
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 322, in set_token
    self.id
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 164, in acquire_token_with_username_password
    return self._acquire_token(token_func)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 162, in token_func
    return token_request.get_token_with_username_password(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 285, in get_token_with_username_password
    token = self._get_token_username_password_federated(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 258, in _get_token_username_password_federated
    username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 210, in _perform_username_password_for_access_token_exchange
    username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 197, in _perform_wstrust_exchange
    result = wstrust.acquire_token(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/wstrust_request.py", line 131, in acquire_token
    raise AdalError('Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.')
adal.adal_error.AdalError: Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azureuser/.ansible/tmp/ansible-tmp-1622072557.7625957-6688-279219788498354/AnsiballZ_azure_rm_resourcegroup.py", line 100, in <module>
    _ansiballz_main()
  File "/home/azureuser/.ansible/tmp/ansible-tmp-1622072557.7625957-6688-279219788498354/AnsiballZ_azure_rm_resourcegroup.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/azureuser/.ansible/tmp/ansible-tmp-1622072557.7625957-6688-279219788498354/AnsiballZ_azure_rm_resourcegroup.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py", line 286, in <module>
  File "/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py", line 282, in main
  File "/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py", line 164, in __init__
  File "/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 449, in __init__
  File "/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1468, in __init__
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 308, in __init__
    self.set_token()
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 326, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/home/azureuser/.local/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 322, in set_token
    self.id
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 164, in acquire_token_with_username_password
    return self._acquire_token(token_func)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/usr/local/lib/python3.6/site-packages/adal/authentication_context.py", line 162, in token_func
    return token_request.get_token_with_username_password(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 285, in get_token_with_username_password
    token = self._get_token_username_password_federated(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 258, in _get_token_username_password_federated
    username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 210, in _perform_username_password_for_access_token_exchange
    username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/token_request.py", line 197, in _perform_wstrust_exchange
    result = wstrust.acquire_token(username, password)
  File "/usr/local/lib/python3.6/site-packages/adal/wstrust_request.py", line 131, in acquire_token
    raise AdalError('Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.')
msrest.exceptions.AuthenticationError: , AdalError: Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 322, in set_token\n    self.id\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 164, in acquire_token_with_username_password\n    return self._acquire_token(token_func)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 128, in _acquire_token\n    return token_func(self)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 162, in token_func\n    return token_request.get_token_with_username_password(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 285, in get_token_with_username_password\n    token = self._get_token_username_password_federated(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 258, in _get_token_username_password_federated\n    username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 210, in _perform_username_password_for_access_token_exchange\n    username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 197, in _perform_wstrust_exchange\n    result = wstrust.acquire_token(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/wstrust_request.py\", line 131, in acquire_token\n    raise AdalError('Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.')\nadal.adal_error.AdalError: Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1622072557.7625957-6688-279219788498354/AnsiballZ_azure_rm_resourcegroup.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1622072557.7625957-6688-279219788498354/AnsiballZ_azure_rm_resourcegroup.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1622072557.7625957-6688-279219788498354/AnsiballZ_azure_rm_resourcegroup.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 286, in <module>\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 282, in main\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 164, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 449, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_ca16qkvc/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1468, in __init__\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 308, in __init__\n    self.set_token()\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 326, in set_token\n    raise_with_traceback(AuthenticationError, \"\", err)\n  File \"/home/azureuser/.local/lib/python3.6/site-packages/msrest/exceptions.py\", line 51, in raise_with_traceback\n    raise error.with_traceback(exc_traceback)\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 322, in set_token\n    self.id\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 164, in acquire_token_with_username_password\n    return self._acquire_token(token_func)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 128, in _acquire_token\n    return token_func(self)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 162, in token_func\n    return token_request.get_token_with_username_password(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 285, in get_token_with_username_password\n    token = self._get_token_username_password_federated(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 258, in _get_token_username_password_federated\n    username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 210, in _perform_username_password_for_access_token_exchange\n    username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 197, in _perform_wstrust_exchange\n    result = wstrust.acquire_token(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/wstrust_request.py\", line 131, in acquire_token\n    raise AdalError('Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.')\nmsrest.exceptions.AuthenticationError: , AdalError: Unsupported wstrust endpoint version. Current support version is wstrust2005 or wstrust13.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

_Copied from original issue: ansible/ansible#74842_

**Comment by rajaniesh** [comment] 2021-05-28 12:40
Can somebody look into this issue please

**Comment by Fred-sun** [comment] 2021-05-31 14:45
@rajaniesh The document's Active Directory username/password as following, Would you give a try?
[default]
azure_ad_user=XXXXX
azure_password=YYYYY
azure_subscription_id=zzzzzzz

**Comment by rajaniesh** [comment] 2021-06-01 04:37
Fred i did the sane but it did not worked

**Comment by Fred-sun** [comment] 2021-06-02 01:42
> Fred i did the sane but it did not worked

@rajaniesh Thanks for your trying! can you share the error that your test!

**Comment by rajaniesh** [comment] 2021-06-03 02:53
Hi Fred,

I just copied the file provided by you and tried it and here is the outcome

[azureuser@vm1 sketch]$ ansible-playbook CreateRg.yml -v
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Aug 24
 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
Using /etc/ansible/ansible.cfg as config file
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Create Azure ResourceGroup] ********************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [localhost]

TASK [Create resource group] *************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to get credentials. Either pass as parameters, set environment variables, define a profile in ~/.azure/credentials, or log in with Azure CLI (`az login`)."}

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


Here is the copy of the credential file

[default]
azure_ad_user=XXXXX
azure_password=YYYYYYY
azure_subscription_id=xyz-xyx-yyyy-iii

and the sample playbook I tried was 

[azureuser@vm1 sketch]$ cat CreateRg.yml
- name: Create Azure ResourceGroup
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: Solutioning_team
      location: eastus


Any clue why Ansible does not work as expected?

Regards
Rajaniesh

**Comment by rajaniesh** [comment] 2021-06-03 15:21
Ansible Team,

Can you please respond.

Regards
Rajaniesh

**Comment by Fred-sun** [comment] 2021-06-07 14:54
@rajaniesh I'm looking at it. Just a moment, please. Thank you!

**Comment by rajaniesh** [comment] 2021-06-12 22:51
Fred Any update ?

**Comment by rajaniesh** [comment] 2021-06-15 13:04
Ansible development team do you have any update on this issue

**Comment by Fred-sun** [comment] 2021-06-15 13:27
> Ansible development team do you have any update on this issue

@rajaniesh I am checking it and will reply to you tomorrow. Thank you!

**Comment by Fred-sun** [comment] 2021-06-15 13:53
@rajaniesh This problem is a known Issue, which is related to azure-cli, and there is no way to solve it for the time being. Azuer-CLI also added error prompts for the time being, but it has not been solved. Please refer to the two links below! Thank you very much!
```e.g.
PR: https://github.com/Azure/azure-cli/pull/11025
Issue: https://github.com/Azure/azure-cli/issues/10979

**Comment by rajaniesh** [comment] 2021-06-15 20:00
Fred,

I am able to login with azure cli without any issue and I still think it is ansible issue I spoke to Microsoft and they told me the issue is from ansible side. If we can not login with user id and password to azure via ansible then why your documentation says that it works but actually it does not work.
Regards 
Rajaniesh

**Comment by rajaniesh** [comment] 2021-06-15 20:49
How do I login to azure with user name and password via ansible that is very basic fundamental question otherwise how my script will work. It is a very basic ask

**Comment by Fred-sun** [comment] 2021-06-16 00:05
@rajaniesh In addition, I have also confirmed this issue with the Microsoft developers. Thank you very much!

**Comment by rajaniesh** [comment] 2021-06-16 00:17
Thanks Fred I have a ansible demo to our management but unable to do so because of this issue. Is there any other alternative wherein we can use ansible with user id and password. Any alternative should work here but pl suggest how we can make it happen. 

Fred, can we use azure cli to login manually and then ansible can take over after it?

**Comment by Fred-sun** [comment] 2021-06-16 00:29
@rajaniesh Of course, for the time being, we can do this via cli, env and credential File. You can use cli mode to operate! Thank you very much!
```e.g.
Step 1: az login
Step 2: az account set -s "sub_id"

**Comment by rajaniesh** [comment] 2021-06-16 01:00
So you are saying if we use this way ansible will be able to login via cli provided credentials without service principal and with azure user id and password. if yes pl provide some code snippet it will be helpful sir

**Comment by Fred-sun** [comment] 2021-06-16 01:55
@rajaniesh After az login, we can directly execute the playbook, and we can do it (ansible will automatically acquire az  login credentials).

```e.g.
 ansible-playbook test.yml

---
- name: Using Azure collection
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: resourceName
  tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: eastus

**Comment by rajaniesh** [comment] 2021-06-16 02:49
Thanks Fred, so I can run azure cli command via ansible shell and then in the next task I can execute azure resource group specific tasks what you mentioned here? Let me try and share the output here.

**Comment by rajaniesh** [comment] 2021-06-16 03:21
Fred,

It is not working

I have followed these steps:
1.changed the credential file to 
[default]
ad_user=XYz
password=yyyyxxxuuu
subscription_id=yuyuyuyubgbgfgf

2.az login I have logged in with the device code
3. az account set -s "sub_id" 
4. ansible-playbook test.yml

It threw this error:

[azureuser@vm1 sketch]$ ansible-playbook test.yml
[WARNING]: Ansible is being run in a world writable directory (/home/azureuser/sketch), ignoring it as an ansible.cfg source. For more
information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Using Azure collection] *************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************
ok: [localhost]

TASK [create resource group] **************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: msrest.exceptions.AuthenticationError: , AdalError: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\r\nTrace ID: 4c378203-3341-46ed-bb52-86387dd21900\r\nCorrelation ID: d23ede65-b341-4ba7-9555-dd1580f48597\r\nTimestamp: 2021-06-16 03:15:54Z","error_codes":[50076],"timestamp":"2021-06-16 03:15:54Z","trace_id":"4c378203-3341-46ed-bb52-86387dd21900","correlation_id":"d23ede65-b341-4ba7-9555-dd1580f48597","error_uri":"https://login.microsoftonline.com/error?code=50076","suberror":"basic_action"}
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 322, in set_token\n    self.id\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 164, in acquire_token_with_username_password\n    return self._acquire_token(token_func)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 128, in _acquire_token\n    return token_func(self)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 162, in token_func\n    return token_request.get_token_with_username_password(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 283, in get_token_with_username_password\n    token = self._get_token_username_password_managed(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 177, in _get_token_username_password_managed\n    return self._oauth_get_token(oauth_parameters)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 112, in _oauth_get_token\n    return client.get_token(oauth_parameters)\n  File \"/usr/local/lib/python3.6/site-packages/adal/oauth2_client.py\", line 289, in get_token\n    raise AdalError(return_error_string, error_response)\nadal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {\"error\":\"interaction_required\",\"error_description\":\"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\\r\\nTrace ID: 4c378203-3341-46ed-bb52-86387dd21900\\r\\nCorrelation ID: d23ede65-b341-4ba7-9555-dd1580f48597\\r\\nTimestamp: 2021-06-16 03:15:54Z\",\"error_codes\":[50076],\"timestamp\":\"2021-06-16 03:15:54Z\",\"trace_id\":\"4c378203-3341-46ed-bb52-86387dd21900\",\"correlation_id\":\"d23ede65-b341-4ba7-9555-dd1580f48597\",\"error_uri\":\"https://login.microsoftonline.com/error?code=50076\",\"suberror\":\"basic_action\"}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1623813352.6712685-1915-110807214856750/AnsiballZ_azure_rm_resourcegroup.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1623813352.6712685-1915-110807214856750/AnsiballZ_azure_rm_resourcegroup.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/azureuser/.ansible/tmp/ansible-tmp-1623813352.6712685-1915-110807214856750/AnsiballZ_azure_rm_resourcegroup.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_m8wlp847/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 286, in <module>\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_m8wlp847/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 282, in main\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_m8wlp847/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 164, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_m8wlp847/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 449, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_m8wlp847/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1468, in __init__\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 308, in __init__\n    self.set_token()\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 326, in set_token\n    raise_with_traceback(AuthenticationError, \"\", err)\n  File \"/home/azureuser/.local/lib/python3.6/site-packages/msrest/exceptions.py\", line 51, in raise_with_traceback\n    raise error.with_traceback(exc_traceback)\n  File \"/usr/local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py\", line 322, in set_token\n    self.id\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 164, in acquire_token_with_username_password\n    return self._acquire_token(token_func)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 128, in _acquire_token\n    return token_func(self)\n  File \"/usr/local/lib/python3.6/site-packages/adal/authentication_context.py\", line 162, in token_func\n    return token_request.get_token_with_username_password(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 283, in get_token_with_username_password\n    token = self._get_token_username_password_managed(username, password)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 177, in _get_token_username_password_managed\n    return self._oauth_get_token(oauth_parameters)\n  File \"/usr/local/lib/python3.6/site-packages/adal/token_request.py\", line 112, in _oauth_get_token\n    return client.get_token(oauth_parameters)\n  File \"/usr/local/lib/python3.6/site-packages/adal/oauth2_client.py\", line 289, in get_token\n    raise AdalError(return_error_string, error_response)\nmsrest.exceptions.AuthenticationError: , AdalError: Get Token request returned http error: 400 and server response: {\"error\":\"interaction_required\",\"error_description\":\"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\\r\\nTrace ID: 4c378203-3341-46ed-bb52-86387dd21900\\r\\nCorrelation ID: d23ede65-b341-4ba7-9555-dd1580f48597\\r\\nTimestamp: 2021-06-16 03:15:54Z\",\"error_codes\":[50076],\"timestamp\":\"2021-06-16 03:15:54Z\",\"trace_id\":\"4c378203-3341-46ed-bb52-86387dd21900\",\"correlation_id\":\"d23ede65-b341-4ba7-9555-dd1580f48597\",\"error_uri\":\"https://login.microsoftonline.com/error?code=50076\",\"suberror\":\"basic_action\"}\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ********************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


It does not work, What changes I have to make here?

Regards
Rajaniesh

**Comment by Fred-sun** [comment] 2021-06-16 04:05
@rajaniesh Please delete .azure/credentials file or change playbook as below:
```e.g.
---
- name: Using Azure collection
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: resourceName
  tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        auth_source: cli
        name: "{{ resource_group }}"
        location: eastus

**Comment by rajaniesh** [comment] 2021-06-16 05:09
Fred,

Thanks for your help it is working now and I have made these changes to make it work seamlessly. I feel Ansible documentation is so poor because this basic thing is not highlighted or provided with the examples.


---
- name: Using Azure collection
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: Rajaniesh-kappan
  tasks:

   - name: Login with CLI credential
     shell: az login -u myusername  -p mySecretePassword
   
- name: set correct subscription
     shell:  az account set -s "subscriptionID"

   - name: create resource group
     azure_rm_resourcegroup:
        auth_source: cli
        name: "{{ resource_group }}"
        location: eastus

But I have another question here How can I avoid hardcoding the credentials in the playbook and take it from ansible-vault. I means to say subscription ID Username and password from vault or text file or config file

Regards
Rajaniesh

**Comment by Fred-sun** [comment] 2021-06-17 08:59
@Akasurde The problem is caused by its dependencies, now we can pass CLI, ENV, Credential or Prameter credentials. Do you have any other questions? If not, I will close it! Thank you very much!

**Comment by rajaniesh** [comment] 2021-06-17 10:49
Thanks Fred, the only question 8s on how to use vault instead of hardcoding the credential in the above playbook while using cli authentication via shell module

**Comment by Fred-sun** [comment] 2021-06-18 07:45
@rajaniesh Yes, We also can config the credential in ~/.azure/credentias or export to env! Thank you very much!
```e.g.
credential file

[default]
subscription_id=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx
client_id=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx
secret=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx
tenant=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx

Or ENV:
export AZURE_SUBSCRIPTION_ID=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx
export AZURE_CLIENT_ID=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx
export AZURE_SECRET=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx
export AZURE_TENANT=xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxxxxxxxxx

**Closed as completed** 2021-08-13 08:18 UTC
Labels: bug, medium-priority, hold
