### ISSUE TITLE
Unable to imeplement OR condition in exclude_host_filtres while creating Azure invenotry.

### ISSUE THREAD

**Issue by ammygill** [ansible/ansible_collections_azure#786] opened 2022-03-18 17:02 UTC
##### SUMMARY
The below tags should be picked up automatically with the OR condition but currently, I have to create two different inventories to create an inventory with the expected Hosts according to the filter.  
(tags.testing is not defined ) or (tags.TESTING is not defined )

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure collection 

##### COLLECTION VERSION
latest

##### STEPS TO REPRODUCE
1) Try to create a Inventory in the AWX or automation controller you will not be able to implement that Filter in the single line with the help of OR condition,  

##### EXPECTED RESULTS
Should be able to filter out with both the TAGs. 

##### ACTUAL RESULTS
--> Need to create a separate Inveontry to implement that Filter.

**Comment by xuzhang3** [comment] 2022-04-01 02:42
@ammygill  Can you share your script?

**Comment by xuzhang3** [comment] 2022-04-01 09:02
@ammygill
VM tags is a bit different from other VM params, it’s a KV map object. The config will looks like: 
```yml
exclude_host_filters:
- "tags['tagkey'] != 'tagValue'"
- "'tagValue' in tags"
```

**Comment by myselfgagandeep** [comment] 2022-04-05 19:11
@xuzhang3 Attaching the source variable file used for filtering hosts:

[azure_rm_source_variable.txt](https://github.com/ansible-collections/azure/files/8421172/azure_rm_source_variable.txt)
 
The filter that you specified works against one tag i.e tagValue, but cannot create a specific OR condition to support multiple tags thereby some hosts with tagValue2 are not discovered.

This works as expected:
```
exclude_host_filters:
- "tags['tagkey'] != 'tagValue'"
```

This does not work:
```
exclude_host_filters:
- "tags['tagkey'] != 'tagValue' or tags['tagkey2'] != 'tagValue2"
```

Trying to get multiple KV support in the exclude filter which seem not to work.

**Comment by xuzhang3** [comment] 2022-04-06 04:33
@myselfgagandeep  should check if the key exists before comparing
```yaml
exclude_host_filters:
- " tags['tagkey'] is defined and tags['tagkey'] == 'tagkey'"
- " tags['tagkey2'] is defined and tags['tagkey2'] == 'tagkey2'"
```

**Comment by myselfgagandeep** [comment] 2022-04-06 18:19
@xuzhang3 : I think what you suggested does the opposite. It removes the hosts which have the keypair. The exclude_host_filters filters out the hosts with these keys and values. Also, the AND condition require both the tags to be present on hosts.
While what i am trying to get is the inventory containing the hosts with the following values:
tagkey: tagvalue1
tagkey2: tagvalue2

Different hosts contain either of these keyvalue pair but not any host will have both of these. Thus we need to have an OR condition to inventory all the hosts having the above pair.

**Comment by myselfgagandeep** [comment] 2022-04-06 18:24
e.g
Host A has assigned tag `tagkey: tagvalue1`
Host B has assigned tag `tagkey2: tagvalue2`

I need to inventory both of these hosts in the Azure inventory.

**Comment by xuzhang3** [comment] 2022-04-07 03:59
@myselfgagandeep  To include hosts only tagged with `tagkey: tagvalue1 ` or `tagkey2: tagvalue2`, the flowing configurations should work:
```yml
exclude_host_filters:
- (tags['tagkey'] is defined and tags['tagkey'] != 'tagkey') or (tags['tagkey2'] is defined and tags['tagkey2'] != 'tagkey2')
```

**Comment by myselfgagandeep** [comment] 2022-04-07 09:30
@xuzhang3 This does not really work. I have tried this earlier but it ignores the condition bypassing the exclude filter and in turn all the hosts with/without tags are pulled inside the inventory.

Is it possible for you to connect over teams or video session some time so i can show the behavior?

**Comment by xuzhang3** [comment] 2022-04-08 04:03
@myselfgagandeep Can you share your script?  this can help me reproduce your issue.

**Comment by myselfgagandeep** [comment] 2022-04-08 06:04
@xuzhang3 Please find the same as attached
[azure_rm_source_variable.txt](https://github.com/ansible-collections/azure/files/8448988/azure_rm_source_variable.txt)

**Comment by xuzhang3** [comment] 2022-04-08 10:00
@myselfgagandeep   Filter :
```yml
exclude_host_filters:
- (tags['tagkey'] is defined and tags['tagkey'] != 'tagkey') or (tags['tagkey2'] is defined and tags['tagkey2'] != 'tagkey2')
```
will works on VMs tagged with `tagkey` or `tagkey2`, those VMs not tagged will not be filtered   

Test result, if `exclude_host_filters` is enabled , VM `xz3-test` and `xz3-test2` will be filterd :
<img width="364" alt="image" src="https://user-images.githubusercontent.com/57888764/162413131-7d3fd221-8913-431b-9d29-75484bcaa309.png">



@ammygill  Does filter
```yml 
exclude_host_filters:
- (tags['tagkey'] is defined and tags['tagkey'] != 'tagkey') or (tags['tagkey2'] is defined and tags['tagkey2'] != 'tagkey2')
```
work in your scenario?

**Comment by myselfgagandeep** [comment] 2022-04-11 11:00
@xuzhang3 I believe we have some understanding issue. We require only `xz3-test` and `xz3-test2` to be part of our inventory which has tags in the inventory and exclude the remaining which are untagged.

`xz3-test` has tags: `tagkey`: `tagvalue1`
`xz3-test2` has tags: `tagkey2`: `tagvalue2`

All the other hosts are not relevant and should be filtered out since we only manage the hosts with the above keyvalue pairs.

**Comment by myselfgagandeep** [comment] 2022-04-11 15:45
@xuzhang3 : Here is how i expect the filter to work containing only two hosts with keyvalue pair present:

![image](https://user-images.githubusercontent.com/44285960/162779131-007b4e0c-fd0c-46c1-83a8-afb8c50d67c1.png)

**Comment by xuzhang3** [comment] 2022-04-12 03:22
@myselfgagandeep   
The filter below will  include VMs that does not have `tagkey:tagkey` or  `tagkey2:tagkey2` tag pairs.
```yaml
exclude_host_filters:
- ((tags['tagkey'] is defined and tags['tagkey'] == 'tagkey') or (tags['tagkey2'] is defined and tags['tagkey2'] == 'tagkey2')) is sameas false
```

**Comment by myselfgagandeep** [comment] 2022-04-12 04:58
@xuzhang3: I need a filter that includes the VM that have `tagkey:tagkey` or `tagkey2:tagkey2` tag pairs. I am repasting my previous statement.

We require only `xz3-test` and `xz3-test2` to be part of our inventory which have below tags in the inventory and exclude the remaining hosts which are untagged.

`xz3-test` has tags: `tagkey: tagvalue1`
`xz3-test2` has tags: `tagkey2: tagvalue2`

These should be included and not excluded. The filter that you shared above does the opposite.

**Comment by xuzhang3** [comment] 2022-04-12 05:42
@myselfgagandeep
`((tags['tagkey'] is defined and tags['tagkey'] == 'tagkey') or (tags['tagkey2'] is defined and tags['tagkey2'] == 'tagkey2')) ` will  include all VM which have `tagekey` or `tagkey2`, combine this expression with ` is sameas false`, all VMs without those tags will match this expression.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/57888764/162889201-850e2995-ed9e-4047-af4d-7e0f64edd2fd.png">

**Comment by myselfgagandeep** [comment] 2022-04-12 05:54
@xuzhang3 : The expression you have used is beneath exclude_host_filters which provides opposite result.

**exclude_host_filters:**
`((tags['tagkey'] is defined and tags['tagkey'] == 'tagkey') or (tags['tagkey2'] is defined and tags['tagkey2'] == 'tagkey2'))`

I wish to **include** the hosts provided by above filter and not **exclude** so that only tagged ones are present.

Example with tags:
```
host1
host2     >> tagkey:tagkey
host3     >> tagkey2:tagkey2
host4
```

So i wish to include `host2` and `host3` based on tags and exclude `host1` and `host4` which are untagged.

**Comment by xuzhang3** [comment] 2022-04-12 06:00
@myselfgagandeep   you missed the ` is sameas false`
exclude_host_filters:
- ((tags['tagkey'] is defined and tags['tagkey'] == 'tagkey') or (tags['tagkey2'] is defined and tags['tagkey2'] == 'tagkey2')) is sameas false

**Comment by myselfgagandeep** [comment] 2022-04-12 07:04
@xuzhang3 : That did it. I have been able successfully exclude the hosts without the specified tags by falsifying the expression as you suggested above. Thanks for help!

**Comment by xuzhang3** [comment] 2022-04-12 09:41
Close this issue, feel free to open another issue if you have questions.

**Closed as completed by xuzhang3** 2022-04-12 09:41 UTC
Labels: question
