### ISSUE TITLE
Cannot pass variables into the dynamic inventory configuration

### ISSUE THREAD

**Issue by PiotrWachulec** [ansible/ansible_collections_azure#1049] opened 2022-12-20 14:14 UTC
##### SUMMARY
I with my team are building the automation platform for deploying and configuring Azure resources. We would like to go with dynamic inventory. Due to the fact that there will be lots of resources, we would like to have the possibility of dynamic configuration of the dynamic resources component. We tried to pass variable to inventory, but without success. Is it bug, is it by design or what is the status?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure.azcollection.azure_rm` - dynamic inventory module

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/testadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.10/dist-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'azure_rm']
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

```yaml
plugin: azure_rm

include_vm_resource_groups:
  - '{{ rg_name }}'

auth_source: cli

plain_host_names: true
```

```
ansible-inventory -i config/inventory.azure_rm.yml --graph -e "rg_name=<redacted>"
```

##### EXPECTED RESULTS

We would like to gather inventory information as usual.

##### ACTUAL RESULTS

```paste below
[WARNING]:  * Failed to parse /home/<redacted>/config/inventory.azure_rm.yml with auto plugin: a batched request failed with status code 404, url /subscriptions/<redacted>/resourceGroups/{{ rg_name }}/providers/Microsoft.Compute/virtualMachines
[WARNING]:  * Failed to parse /home/<redacted>/config/inventory.azure_rm.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /home/<redacted>/config/inventory.azure_rm.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is reserved to provide a port.
[WARNING]:  * Failed to parse /home/<redacted>/config/inventory.azure_rm.yml with ansible_collections.azure.azcollection.plugins.inventory.azure_rm plugin: a batched request failed with status code 404, url /subscriptions/<redacted>/resourceGroups/{{ rg_name
}}/providers/Microsoft.Compute/virtualMachines
[WARNING]: Unable to parse /home/<redacted>/config/inventory.azure_rm.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
@all:
  |--@ungrouped:
```

**Comment by Fred-sun** [comment] 2022-12-22 07:51
@PiotrWachulec Great problem description, we will find the cause and fix it as soon as possible. Thanks!

**Comment by PiotrWachulec** [comment] 2022-12-22 08:20
Thanks a lot, it will be soooo much helpful! Really thanks, and I'm waiting for the solution! :)

**Comment by akira6592** [comment] 2022-12-27 04:17
Interesting for me as well.

For your information, I previously fixed the `netbox.netbox.nb_inventory` inventory plugin to pass variables for some parameters.
https://github.com/netbox-community/ansible_modules/pull/834

Subsequently, it was modified a bit.
https://github.com/netbox-community/ansible_modules/pull/861

**Comment by PiotrWachulec** [comment] 2023-01-03 08:01
Hey @Fred-sun, had you any chance to look at this issue?

**Comment by akira6592** [comment] 2023-02-10 12:57
@PiotrWachulec 

FYI. If you can use environment variable, there is also a way to use `ANSIBLE_AZURE_VM_RESOURCE_GROUPS`.

```yaml
plugin: azure_rm
auth_source: cli
plain_host_names: true
```

```
ANSIBLE_AZURE_VM_RESOURCE_GROUPS=rg1,rg2 ansible-inventory -i config/inventory.azure_rm.yml --graph
```

This method was added in  #975, but unfortunately has not been released yet.

**Comment by PiotrWachulec** [comment] 2023-02-15 09:59
Hi @akira6592! Looks very promising, something which I need! @Fred-sun when will it be released?

**Comment by Fred-sun** [comment] 2023-02-21 13:46
@PiotrWachulec @akira6592 Sorry for replying you so late. We will release the latest changes after reviewing them. Please forgive me for the trouble! Thanks!

**Comment by Fred-sun** [comment] 2023-02-22 03:21
Because of #975 has merged！I will push to release 1.15.0 and close this issue! Thank you very much!

**Closed as completed by Fred-sun** 2023-02-22 03:21 UTC
Labels: bug, inventory, medium-priority, working

**Comment by PiotrWachulec** [comment] 2023-02-22 07:25
@Fred-sun Great to hear! When can we expect 1.15.0 release?

**Comment by Fred-sun** [comment] 2023-02-22 07:46
@PiotrWachulec Working on! Thank you very much!
