### ISSUE TITLE
Private dns name

### ISSUE THREAD

**Issue by zaskan** [ansible/ansible_collections_azure#149] opened 2020-06-08 07:52 UTC
##### SUMMARY

How to get private dns name

##### COMPONENT NAME

Azure modules

##### EXPECTED RESULTS

The aws module returns the private fqdn name using the private_dns_name variable. How can this be performed by azure modules? Is there any way to override ansible_host variable with fqdn name? It must be done in this way in order to use kerberos and azure dynamic inventory.

**Comment by Fred-sun** [comment] 2020-07-30 06:55
@zaskan Thank you for submitting this question. Can you describe this requirement clearly? what is the purpose of this requirement? In addition, I tried to obtain the private dns information as follows, is it what you need?
```e.g.
            "azure_privatednszones": [
                {
                    "etag": "xxxxxxxxxxxxxx",
                    "id": "/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/v-xisurg/providers/Microsoft.Network/privateDnsZones/b57dc95985712e4550217.com",
                    "location": "global",
                    "name": "b57dc95985712e4550217.com",
                    "properties": {
                        "maxNumberOfRecordSets": 25000,
                        "maxNumberOfVirtualNetworkLinks": 1000,
                        "maxNumberOfVirtualNetworkLinksWithRegistration": 100,
                        "numberOfRecordSets": 1,
                        "numberOfVirtualNetworkLinks": 0,
                        "numberOfVirtualNetworkLinksWithRegistration": 0,
                        "provisioningState": "Succeeded"
                    },
                    "tags": {
                        "test": "modified"
                    },
                    "type": "Microsoft.Network/privateDnsZones"
                }
            ]

**Comment by Fred-sun** [comment] 2020-08-05 07:10
Not a bug, I will close it!

**Closed as completed by Fred-sun** 2020-08-05 07:10 UTC
