### ISSUE TITLE
azure_rm_rediscache_info errors on access keys retrieval if name is not passed as a parameter. 

### ISSUE THREAD

**Issue by JulienPlantier** [ansible/ansible_collections_azure#340] opened 2020-11-30 16:02 UTC
##### SUMMARY
azure_rm_rediscache_info errors on access keys retrieval if name is not passed as a parameter. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_rediscache_info

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/plantier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Windows / Azure Redis Cache

##### STEPS TO REPRODUCE
Just run a playbook with a task azure_rm_rediscache_info that doesn't specify the name of the redis cache but sets return_access_keys to true:
```
- hosts: localhost
  tasks :
    - name: Get Azure Cache for Redis with access keys by tag
      azure.azcollection.azure_rm_rediscache_info:
        resource_group: "resource_group_name"
        tags: 
          - "tag:value"
        return_access_keys: true
      register: redis_infos
```

##### EXPECTED RESULTS
The redis cache facts in redis_infos.

##### ACTUAL RESULTS
The ansible run fails with a ValidationError on the name parameter in RedisManagementClient list_keys.

```The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1606741715.0554795-7726-74031551035748/AnsiballZ_azure_rm_rediscache_info.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1606741715.0554795-7726-74031551035748/AnsiballZ_azure_rm_rediscache_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1606741715.0554795-7726-74031551035748/AnsiballZ_azure_rm_rediscache_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_rediscache_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_rediscache_info.py", line 353, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_rediscache_info.py", line 349, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_rediscache_info.py", line 237, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 436, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_rediscache_info.py", line 256, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_rediscache_info.py", line 291, in list_by_resourcegroup
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_rediscache_info.py", line 337, in serialize_rediscache
  File "/tmp/ansible_azure.azcollection.azure_rm_rediscache_info_payload_ivuhjw63/ansible_azure.azcollection.azure_rm_rediscache_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_rediscache_info.py", line 303, in list_keys
  File "/root/.venv/xxx/lib64/python3.6/site-packages/azure/mgmt/redis/operations/redis_operations.py", line 542, in list_keys
    'name': self._serialize.url("name", name, 'str'),
  File "/root/.venv/xxx/lib64/python3.6/site-packages/msrest/serialization.py", line 591, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/root/.venv/xxx/lib64/python3.6/site-packages/msrest/serialization.py", line 661, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'name' can not be None.
```

This is due to list_keys using the variable self.name https://github.com/ansible-collections/azure/blob/1ec66ace6012f7ae757f454d7c5701bb666188ea/plugins/modules/azure_rm_rediscache_info.py#L303 to retrieve the access keys when called in serialize_rediscache.
It should instead use the name of the rediscache object retrieved in list_by_resourcegroup.

An easy workaround is to use two azure_rm_rediscache_info tasks, one to retrieve the name and one to retrieve the access keys using the name.

**Comment by Fred-sun** [comment] 2020-12-21 02:33
@JulienPlantier Thank you for reporting this issue. When return_access_keys is set to True, the parameter name must be configured, thank you!

**Comment by Fred-sun** [comment] 2021-01-12 02:22
@JulienPlantier It's not a bug, I will close it!

**Closed as completed by Fred-sun** 2021-01-12 02:22 UTC
Labels: medium-priority, working
