### ISSUE TITLE
azure_keyvault_secret doesn't take credentials from credential file

### ISSUE THREAD

**Issue by eeepmb** [ansible/ansible_collections_azure#1178] opened 2023-06-02 11:15 UTC
##### SUMMARY

When using azure_keyvault_secret lookup plugin and azure credentials set via credential file I run into the following error. Setting credentials via env vars fixes this error.

```
original message: An unhandled exception occurred while templating '{{ lookup('azure.azcollection.azure_keyvault_secret', secret_name, vault_url=vault_url) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'TypeError'>, original message: can only concatenate str (not \"NoneType\") to str. can only concatenate str (not \"NoneType\") to str
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

[azure.azcollection.azure_keyvault_secret lookup](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_keyvault_secret_lookup.html)

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/azureuser/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/azureuser/.local/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 1.15.0 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Read summary above.

```yaml
test_var: "{{ lookup('azure.azcollection.azure_keyvault_secret', secret_name, vault_url=vault_url) }}"
```

##### EXPECTED RESULTS

Plugin should use credential file like [azure_rm inventory](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html#parameter-auth_source)

##### ACTUAL RESULTS

```paste below
Error was a <class 'TypeError'>, original message: can only concatenate str (not \"NoneType\") to str. can only concatenate str (not \"NoneType\") to str
```

**Comment by Fred-sun** [comment] 2023-06-28 02:39
@eeepmb Cou you share your full playbook? It will help to solve this problem, Thank you very much!

**Comment by Fred-sun** [comment] 2023-06-28 02:41
@eeepmb It is best to provide you with the full process for reproducing the problem. Thank you very much!

**Comment by eeepmb** [comment] 2023-07-04 09:33
Hi @Fred-sun unfortunately I can't share the full playbook but I'm gonna share the essential bits below.

The mentioned credential file: 
```bash
$ cat ~/.azure/credentials 
[default]
subscription_id=***
client_id=***
secret=***
tenant=***
```

Inventory plugin and group vars: 

```
# azure_rm.yml

plugin: azure.azcollection.azure_rm

auth_source: auto

cloud_environment: AzureCloud

groups:
keyed_groups:
  - key: tags.Function
    separator: ''


# playbooks/group_vars/all.yml

test_var: "{{ lookup('azure.azcollection.azure_keyvault_secret', secret_name, vault_url=vault_url) }}"
```

So now when I'm going to create an inventory and run my playbooks against it `ansible-inventory` works but `ansible-playbook` fails because `azure.azcollection.azure_keyvault_secret` misses the credentials for Azure:

```bash
ansible-inventory -i azure_rm.yml --y --list --output inventory/snapshot.yml
ansible-playbook -i inventory/snapshot.yml playbooks/test.yml"
```

`ansible-playbook` leads to: `original message: An unhandled exception occurred while templating '{{ lookup('azure.azcollection.azure_keyvault_secret', secret_name, vault_url=vault_url) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'TypeError'>, original message: can only concatenate str (not \"NoneType\") to str. can only concatenate str (not \"NoneType\") to str`

When adding my Azure credentials per env vars like below and rerunning the playbook Ansible can access the secret in the Key Vault.

```bash
$ cat ~/.bashrc
...
export AZURE_CLIENT_ID=***
export AZURE_SECRET=***
export AZURE_TENANT=***
```

It would be great if `azure.azcollection.azure_keyvault_secret` would also use `"cli"`, `"credential_file"` and `"msi"` besides `"env"` as [`auth_source`](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html#parameter-auth_source).

Hope this clears things up. Let me know if you have further questions.

BR

**Comment by Fred-sun** [comment] 2023-07-05 06:22
Hi eeepmb:
      Welcome to the issue you submitted, which has been fixed in v1.16.0.
      When the parameters in the function ServicePrincipalCredentials is None, you will be prompted to encounter you mentioned error.

      You can update to the latest version and test that the new version evaluates the parameters to avoid the error of None.  --------- update method: ansible-galaxy collection install azure.azcollection --force

      Thank you!

________________________________
发件人: eeepmb ***@***.***>
发送时间: Tuesday, July 4, 2023 5:33:47 PM
收件人: ansible-collections/azure ***@***.***>
抄送: Fred Sun (PACTERA TECHNOLOGIES INC) ***@***.***>; Mention ***@***.***>
主题: Re: [ansible-collections/azure] azure_keyvault_secret doesn't take credentials from credential file (Issue #1178)


Hi @Fred-sun<https://github.com/Fred-sun> unfortunately I can't share the full playbook but I'm gonna share the essential bits below.

The mentioned credential file:

$ cat ~/.azure/credentials
[default]
subscription_id=***
client_id=***
secret=***
tenant=***

Inventory plugin and group vars:

# azure_rm.yml

plugin: azure.azcollection.azure_rm

auth_source: auto

cloud_environment: AzureCloud

groups:
keyed_groups:
  - key: tags.Function
    separator: ''


# playbooks/group_vars/all.yml

test_var: "{{ lookup('azure.azcollection.azure_keyvault_secret', secret_name, vault_url=vault_url) }}"


So now when I'm going to create an inventory and run my playbooks against it ansible-inventory works but ansible-playbook fails because azure.azcollection.azure_keyvault_secret misses the credentials for Azure:

ansible-inventory -i azure_rm.yml --y --list --output inventory/snapshot.yml
ansible-playbook -i inventory/snapshot.yml playbooks/test.yml"

ansible-playbook leads to: original message: An unhandled exception occurred while templating '{{ lookup('azure.azcollection.azure_keyvault_secret', secret_name, vault_url=vault_url) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'TypeError'>, original message: can only concatenate str (not \"NoneType\") to str. can only concatenate str (not \"NoneType\") to str

When adding my Azure credentials per env vars like below and rerunning the playbook Ansible can access the secret in the Key Vault.

$ cat ~/.bashrc
...
export AZURE_CLIENT_ID=***
export AZURE_SECRET=***
export AZURE_TENANT=***

It would be great if azure.azcollection.azure_keyvault_secret would also use "cli", "credential_file" and "msi" besides "env" as auth_source<https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_inventory.html#parameter-auth_source>.

Hope this clears things up. Let me know if you have further questions.

BR

―

**Comment by Fred-sun** [comment] 2023-07-05 06:23
@eeepmb Which has been fixed in v1.16.0.  You can upgrade to the lasted version to retry .
update method： nnsible-galaxy collection install azure.azcollection --force

**Comment by Fred-sun** [comment] 2023-11-30 07:53
@eeepmb I'm sorry for not solving your problem so quickly. Since azure_keyvault_secret.py is a plugin, the previous design was to pass its parameters directly in playbook. If we're going to consider credentials_file, we also have to consider the way environment variables and so on are passed. The purpose of the plugin is to get your information easily and quickly. So no information from credentials_file! Thank you!

**Comment by eeepmb** [comment] 2023-11-30 09:42
@Fred-sun no problem. 
Still I think from an user perspective it would be great if all azure plugins are consistent and adapt to auth methods from azure cli.
I was expecting that both plugins use to same methods to pass credentials under the hood.

BR

**Comment by Fred-sun** [comment] 2023-12-01 00:29
@eeepmb Thank you for your reply, we will discuss the support for all methods internally, thank you!

**Closed as completed by Fred-sun** 2023-12-01 00:29 UTC
Labels: question, medium-priority, not-a-bug, working
